name: Builder

on:
  workflow_dispatch:
  

jobs:
  builder:
    strategy:
    env:
      branch: phoenix-r-oss
      
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 20480
          temp-reserve-mb: 10240
          swap-size-mb: 10240
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
      - name: Setup java
        uses: action/setup-java@v3
        with:
          