name: Builder

on:
  workflow_dispatch:
  

jobs:
  builder:
    strategy:
    env:
      branch: phoenix-r-oss
      
    runs-on: ubuntu-latest
    steps:
      - name: Setup java
        uses: action/setup-java@v3
        with:
          