name: Builder

on:
  workflow_dispatch:
  push:
    branches:
      - main # default branch

jobs:
  builder:
    env:
      branch: phoenix-r-oss
      ref-tag: LA.UM.9.1.r1-06700-SMxxx0.0-1
      debug: true
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 20480
          temp-reserve-mb: 10240
          swap-size-mb: 10240
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
      - name: Install Environment
        run: |
         sudo apt update
         sudo apt install openjdk-8-jdk
         sudo apt install repo
      - name: Get kernel source
        run: |
         git clone -b ${{ env.branch }} https://github.com/MiCode/Xiaomi_Kernel_OpenSource.git
      - name: print log
        if: ${{ env.debug == 'true' }}
        run: |
         cd Xiaomi_Kernel_OpenSource
         git log
      - name: Get QAEP
        run: |
         mkdir QAEP
         cd QAEP
         repo init -u git://codeaurora.org/platform/manifest.git -b release -m ${{ env.ref-tag }}.xml --repo-url=git://codeaurora.org/tools/repo.git --repo-branch=caf-stable
         repo sync -j$(nproc)
